server:
  port: 8094
  tomcat:
    uri-encoding: UTF-8
  servlet:
    context-path: /seata
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/seata-demo?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8&allowMultiQueries=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

dubbo:
  application:
    name: seata
  consumer:
    check: false
  registry:
    check: false
    protocol: nacos
    address: nacos://127.0.0.1:8848?namespace=f3972b84-6d85-4b31-b0d3-88e8079cc23a
  protocol:
    name: seata
    port: 18094

seata:
  enabled: true
  application-id: seata-demo  #可自定义
  tx-service-group: my_test_tx_group #事务组名可自定义，但必须与配置中心参数一致
  enable-auto-data-source-proxy: true #数据源自动代理
  service:
    grouplist:
      default: 172.22.12.48:8091
    vgroup-mapping:
      my_test_tx_group: default
    enable-degrade: false
    disable-global-transaction: false

  mybatis-plus:
    mapper-locations: classpath:sqlmap/auto/*.xml
    configuration:
      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

